User.create(name: "Miki Dora", email: "dora@email.com", password: "12345")
User.create(name: "Mick Fanning", email: "fanning@email.com", password: "12345")
User.create(name: "Kelly Slater", email: "slater@email.com", password: "12345")
User.create(name: "Wiggy", email: "wiggy@email.com", password: "12345")
User.create(name: "Pitchouli Bob", email: "bob@email.com", password: "12345")
User.create(name: "Ashley Stevens", email: "stevens@email.com", password: "12345")
User.create(name: "Slugo", email: "slugo@email.com", password: "12345")
User.create(name: "Phil Edwards", email: "philly@email.com", password: "12345")
User.create(name: "Nat Young", email: "nat@email.com", password: "12345")
User.create(name: "Bethany Hamilton", email: "hamilton@email.com", password: "12345")
User.create(name: "Jerricho Poppler", email: "poppler@email.com", password: "12345")
User.create(name: "Lance Burkhart", email: "burkhart@email.com", password: "12345")
User.create(name: "Michael Pieschel", email: "mike@surferslog.com", admin: true, password: "12345")

SurfSpot.create(name: "Malibu, CA")
SurfSpot.create(name: "Bells Beach")
SurfSpot.create(name: "Pipeline, HI")
SurfSpot.create(name: "Lower Trestles, CA")
SurfSpot.create(name: "Surf Ranch, CA")
SurfSpot.create(name: "Seal Beach, CA")
SurfSpot.create(name: "Waimea Bay, HI")
SurfSpot.create(name: "Teahupoo")
SurfSpot.create(name: "Trestles, CA") 
SurfSpot.create(name: "Morro Bay, CA") 

Country.create(name: "USA")
Country.create(name: "Australia")
Country.create(name: "Tahiti")
Country.create(name: "Brazil")
Country.create(name: "Canada‎")
Country.create(name: "Chile‎")
Country.create(name: "Costa Rica‎")
Country.create(name: "Ecuador")
Country.create(name: "France‎")
Country.create(name: "Indonesia‎")
Country.create(name: "Ireland‎")
Country.create(name: "New Zealand‎")
Country.create(name: "Pakistan")
Country.create(name: "Peru‎")
Country.create(name: "the Philippines‎")
Country.create(name: "South Africa")
Country.create(name: "the United Kingdom")

LogEntry.create(user_id: 1, surf_spot_id: 1, country_id: 1, swell_size: "5ft", swell_direction: "SW", conditions: "Side shore wind", wave_count: "100", image_url: "/images/malibu2.jpg", date: 19600715)
LogEntry.create(user_id: 2, surf_spot_id: 2, country_id: 2, swell_size: "", swell_direction: "", conditions: "", wave_count: "34", image_url: "/images/fanning.jpg", date: 20110603)
LogEntry.create(user_id: 3, surf_spot_id: 3, country_id: 3, swell_size: "Double Overhead", swell_direction: "Northwest", conditions: "Clean", wave_count: "20-30", image_url: "/images/pipeline.jpg", date: 20050130)
LogEntry.create(user_id: 3, surf_spot_id: 4, country_id: 1, swell_size: "", swell_direction: "", conditions: "", wave_count: "", image_url: "/images/trestles.jpg", date: 20161110)
LogEntry.create(user_id: 3, surf_spot_id: 5, country_id: 1, swell_size: "", swell_direction: "", conditions: "Mechanical", wave_count: "", image_url: "/images/surfranchkellyslater.jpg", date: 20160812)
LogEntry.create(user_id: 4, surf_spot_id: 6, country_id: 1, swell_size: "Massive", swell_direction: "", conditions: "Stormy", wave_count: "Just this one!", image_url: "/images/seal_pier.jpg", date: 19830211)
LogEntry.create(user_id: 5, surf_spot_id: 1, country_id: 1, swell_size: "Huge", swell_direction: "south southwest", conditions: "Decent", wave_count: "10", image_url: "/images/malibu3.jpg", date: 20140820)
LogEntry.create(user_id: 6, surf_spot_id: 6, country_id: 1, swell_size: "Chest high", swell_direction: "West", conditions: "cold and clean winter morning", wave_count: "8(all i need)", image_url: "/images/seal_beach_pier.jpg", date: 20141214)
LogEntry.create(user_id: 7, surf_spot_id: 6, country_id: 1, swell_size: "", swell_direction: "", conditions: "Far out", wave_count: "?", image_url: "/images/sb_pier.jpg", date: 20090106)
LogEntry.create(user_id: 8, surf_spot_id: 7, country_id: 1, swell_size: "Big as a barn", swell_direction: "", conditions: "", wave_count: "35", image_url: "/images/waimea_Bay.jpg", date: 19650210)
LogEntry.create(user_id: 9, surf_spot_id: 2, country_id: 2, swell_size: "", swell_direction: "", conditions: "", wave_count: "Millions", image_url: "/images/bellsbeach.jpg", date: 19750503)
LogEntry.create(user_id: 10, surf_spot_id: 8, country_id: 3, swell_size: "SSSOOOOO BBBIIIIGGGG!!!", swell_direction: "SSW and S mix", conditions: "GREAT!", wave_count: "", image_url: "/images/teahupoo.jpg", date: 20090615)
LogEntry.create(user_id: 11, surf_spot_id: 9, country_id: 1, swell_size: "Chest high", swell_direction: "", conditions: "kinda frothy but lots of sun", wave_count: "21", image_url: "/images/jerricho.jpg", date: 19790623)
LogEntry.create(user_id: 12, surf_spot_id: 1, country_id: 1, swell_size: "", swell_direction: "", conditions: "", wave_count: "", image_url: "/images/malibu.jpg", date: 19590801)
LogEntry.create(user_id: 13, surf_spot_id: 3, country_id: 1, swell_size: "4-6ft", swell_direction: "NW", conditions: "Hard off shore", wave_count: "infinity", image_url: "/images/mikesurf3.jpg", date: 20121221)
LogEntry.create(user_id: 13, surf_spot_id: 10, country_id: 1, swell_size: "Head high", swell_direction: "", conditions: "", wave_count: "a ton", image_url: "/images/mikeysurf1.jpg", date: 20130118)

Post.create(log_entry_id: 1, user_id: 1, content: "I'm the king of malibu! No hodad can top this hotdogger! I surfed every single wave in the curl all day!")
Post.create(log_entry_id: 2, user_id: 2, content: "Crikey, what a blast! I got so tubed! After every tube I was frothin' for more, mate!")
Post.create(log_entry_id: 3, user_id: 3, content: "What can I say? Best waves of my life? Always trying to get that epic sesh!")
Post.create(log_entry_id: 4, user_id: 3, content: "It got really packed! Even though I'm the most famous surfer in the world I still have to fight for waves!")
Post.create(log_entry_id: 5, user_id: 3, content: "Sometimes you just have to build the perfect wave and fense it in to get waves to yourself.")
Post.create(log_entry_id: 6, user_id: 4, content: "The storm broke the pier in half! I paddle out and got this one from the boneyard! One and done!")
Post.create(log_entry_id: 7, user_id: 5, content: "Hurricane Marie was pumpin, man! Couldn't believe how solid the waves were. Oh, man. You should have been there!")
Post.create(log_entry_id: 8, user_id: 6, content: "OMG! I love surfing seal when it's that good! So fun!")
Post.create(log_entry_id: 9, user_id: 7, content: "Man, I got some humdingers and a couple of whoppers! One wave was a doozy!")
Post.create(log_entry_id: 10, user_id: 8, content: "Well, the surf session was really swell. Ha! Ya see what I did there?")
Post.create(log_entry_id: 11, user_id: 9, content: "Damn! It was epic! Best Day ever!")
Post.create(log_entry_id: 12, user_id: 10, content: "After locking in Teahupoo like I did today everyone will know I can hold my own in the world of Surfing!")
Post.create(log_entry_id: 13, user_id: 11, content: "Wow! Do I look great! I love that bathing suit! I was on the nose and carving the curl all day!")
Post.create(log_entry_id: 14, user_id: 12, content: "For all who were out surfing, I have a message. Don't Snake Me!")
Post.create(log_entry_id: 15, user_id: 13, content: "SSSSSSSSSSUUUUUUUUUUUUUUURRRRRRRRFFFFFF!!!! I love surfing!  I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing!")
Post.create(log_entry_id: 16, user_id: 13, content: "I had to give a hard stare to all the kooks in the water that day so they wouldn't try to burn me!")

Post.create(log_entry_id: 11, user_id: 13, content: "I'm Drooling over that photo man!")
Post.create(log_entry_id: 3, user_id: 13, content: "You're my idol.")
Post.create(log_entry_id: 5, user_id: 13, content: "WWWWWwhhhhhhhhaaaattttt!?")
Post.create(log_entry_id: 5, user_id: 1, content: "This place stinks!")
Post.create(log_entry_id: 5, user_id: 4, content: "Nothing authentic going on here.")
Post.create(log_entry_id: 9, user_id: 6, content: "Love it! Surfing here is so fun!")
Post.create(log_entry_id: 13, user_id: 8, content: "Born and raised surfing this spot. Always worth the sinus infections.")
Post.create(log_entry_id: 1, user_id: 9, content: "Dude!")
Post.create(log_entry_id: 13, user_id: 7, content: "I surfed Seal Beach Jetty that day. Looks like I should have made the drive.")
Post.create(log_entry_id: 16, user_id: 13, content: "Did I mention the kooks?")
Post.create(log_entry_id: 2, user_id: 11, content: "Wow! I need to get back to Oz.")
Post.create(log_entry_id: 12, user_id: 8, content: "Never seen anything like it!")
Post.create(log_entry_id: 10, user_id: 11, content: "Nice!")
Post.create(log_entry_id: 10, user_id: 8, content: "You get it!? :)")
Post.create(log_entry_id: 4, user_id: 9, content: "I can remember what it felt like to surf alone.")
Post.create(log_entry_id: 8, user_id: 2, content: "I was once attacked by a shark. I felt like a helpless seal.")
Post.create(log_entry_id: 1, user_id: 13, content: "Old School!")
