User.create(name: "Miki Dora", email: "dora@email.com", password: "12345")
User.create(name: "Mick Fanning", email: "fanning@email.com", password: "12345")
User.create(name: "Kelly Slater", email: "slater@email.com", password: "12345")
User.create(name: "Wiggy", email: "wiggy@email.com", password: "12345")
User.create(name: "Pitchouli Bob", email: "bob@email.com", password: "12345")
User.create(name: "Ashley Stevens", email: "stevens@email.com", password: "12345")
User.create(name: "Slugo", email: "slugo@email.com", password: "12345")
User.create(name: "Phil Edwards", email: "philly@email.com", password: "12345")
User.create(name: "Nat Young", email: "nat@email.com", password: "12345")
User.create(name: "Bethany Hamilton", email: "hamilton@email.com", password: "12345")
User.create(name: "Jerricho Poppler", email: "poppler@email.com", password: "12345")
User.create(name: "Lance Burkhart", email: "burkhart@email.com", password: "12345")
User.create(name: "Michael Pieschel", email: "mike@surferslog.com", admin: true, password: "12345")

Country.create(name: "USA")
Country.create(name: "Australia")
Country.create(name: "Tahiti")
Country.create(name: "Brazil")
Country.create(name: "Canada‎")
Country.create(name: "Chile‎")
Country.create(name: "Costa Rica‎")
Country.create(name: "Ecuador")
Country.create(name: "France")
Country.create(name: "Indonesia‎")
Country.create(name: "New Zealand‎")
Country.create(name: "Algeria")
Country.create(name: "Angola")
Country.create(name: "Cape Verde")
Country.create(name: "Ghana")
Country.create(name: "Ivory Coast")
Country.create(name: "Liberia")
Country.create(name: "Madagascar")
Country.create(name: "Mauritius")
Country.create(name: "Morocco")
Country.create(name: "Mozambique")
Country.create(name: "Namibia")
Country.create(name: "Nigeria")
Country.create(name: "Senegal")
Country.create(name: "Swaziland")
Country.create(name: "São Tomé and Príncipe")
Country.create(name: "China")
Country.create(name: "Hong Kong")
Country.create(name: "India")
Country.create(name: "Israel")
Country.create(name: "Japan")
Country.create(name: "Lebanon")
Country.create(name: "Malaysia")
Country.create(name: "Maldives")
Country.create(name: "Palestine")
Country.create(name: "Russia")
Country.create(name: "South Korea")
Country.create(name: "Sri Lanka")
Country.create(name: "Taiwan")
Country.create(name: "Thailand")
Country.create(name: "Turkey")
Country.create(name: "Belgium")
Country.create(name: "Bulgaria")
Country.create(name: "Cyprus")
Country.create(name: "Denmark")
Country.create(name: "Finland")
Country.create(name: "Germany")
Country.create(name: "Greece")
Country.create(name: "Guernsey")
Country.create(name: "Iceland")
Country.create(name: "Ireland")
Country.create(name: "Italy")
Country.create(name: "Jersey")
Country.create(name: "Latvia")
Country.create(name: "Netherlands")
Country.create(name: "Norway")
Country.create(name: "Poland")
Country.create(name: "Portugal")
Country.create(name: "Romania")
Country.create(name: "Spain")
Country.create(name: "Sweden")
Country.create(name: "Aruba")
Country.create(name: "Bahamas")
Country.create(name: "Barbados")
Country.create(name: "British Virgin Islands")
Country.create(name: "Cuba")
Country.create(name: "Curaçao")
Country.create(name: "Dominica")
Country.create(name: "Dominican Republic")
Country.create(name: "El Salvador")
Country.create(name: "Grenada")
Country.create(name: "Guadeloupe")
Country.create(name: "Guatemala")
Country.create(name: "Jamaica")
Country.create(name: "Martinique")
Country.create(name: "Mexico")
Country.create(name: "Nicaragua")
Country.create(name: "Panama")
Country.create(name: "Puerto Rico")
Country.create(name: "St Lucia")
Country.create(name: "Trinidad and Tobago")
Country.create(name: "U.S. Virgin Islands")
Country.create(name: "Fiji")
Country.create(name: "French Polynesia")
Country.create(name: "Guam")
Country.create(name: "Marshall Islands")
Country.create(name: "Micronesia")
Country.create(name: "New Caledonia")
Country.create(name: "Papua New Guinea")
Country.create(name: "Samoa")
Country.create(name: "Solomon Islands")
Country.create(name: "Tonga")
Country.create(name: "Argentina")
Country.create(name: "Colombia")
Country.create(name: "Uruguay")
Country.create(name: "Venezuela")
Country.create(name: "Peru‎")
Country.create(name: "Philippines")
Country.create(name: "South Africa")
Country.create(name: "United Kingdom")

SurfSpot.create(name: "Malibu, CA", country_id: 1)
SurfSpot.create(name: "Bells Beach", country_id: 2)
SurfSpot.create(name: "Pipeline, HI", country_id: 1)
SurfSpot.create(name: "Lower Trestles, CA", country_id: 1)
SurfSpot.create(name: "Surf Ranch, CA", country_id: 1)
SurfSpot.create(name: "Seal Beach, CA", country_id: 1)
SurfSpot.create(name: "Waimea Bay, HI", country_id: 1)
SurfSpot.create(name: "Teahupoo", country_id: 3)
SurfSpot.create(name: "Trestles, CA", country_id: 1) 
SurfSpot.create(name: "Morro Bay, CA", country_id: 1) 

LogEntry.create(user_id: 1, public: true, surf_spot_id: 1, country_id: 1, rating: nil, swell_1_size: 5, swell_1_direction: "SW", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: 8, wind_direction: "NE", wave_count: 40, image_url: "/images/malibu2.jpg", date: 19600715, time: nil)
LogEntry.create(user_id: 2, public: true, surf_spot_id: 2, country_id: 2, rating: 5, swell_1_size: nil, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: 24, image_url: "/images/fanning.jpg", date: 20110603, time: nil)
LogEntry.create(user_id: 3, public: true, surf_spot_id: 3, country_id: 1, rating: 5, swell_1_size: 8, swell_1_direction: "NW", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: 5, wind_direction: "SE", wave_count: 15, image_url: "/images/pipeline.jpg", date: 20050130, time: nil)
LogEntry.create(user_id: 3, public: true, surf_spot_id: 4, country_id: 1, rating: 4, swell_1_size: nil, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: nil, image_url: "/images/trestles.jpg", date: 20161110, time: nil)
LogEntry.create(user_id: 3, public: true, surf_spot_id: 5, country_id: 1, rating: nil, swell_1_size: nil, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: 0, wind_direction: "Glassy", wave_count: nil, image_url: "/images/surfranchkellyslater.jpg", date: 20160812, time: nil)
LogEntry.create(user_id: 4, public: true, surf_spot_id: 6, country_id: 1, rating: 3, swell_1_size: 15, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: 5, wind_direction: "NW", wave_count: 1, image_url: "/images/seal_pier.jpg", date: 19830211, time: nil)
LogEntry.create(user_id: 5, public: true, surf_spot_id: 1, country_id: 1, rating: nil, swell_1_size: 13, swell_1_direction: "SW", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: 10, image_url: "/images/malibu3.jpg", date: 20140820, time: nil)
LogEntry.create(user_id: 6, public: true, surf_spot_id: 6, country_id: 1, rating: 5, swell_1_size: 5, swell_1_direction: "W", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: 3, wind_direction: "ESE", wave_count: 8, image_url: "/images/seal_beach_pier.jpg", date: 20141214, time: nil)
LogEntry.create(user_id: 7, public: true, surf_spot_id: 6, country_id: 1, rating: nil, swell_1_size: nil, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: 8, wind_direction: "NW", wave_count: nil, image_url: "/images/sb_pier.jpg", date: 20090106, time: nil)
LogEntry.create(user_id: 8, public: true, surf_spot_id: 7, country_id: 1, rating: nil, swell_1_size: 20, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: 35, image_url: "/images/waimea_Bay.jpg", date: 19650210, time: nil)
LogEntry.create(user_id: 9, public: true, surf_spot_id: 2, country_id: 2, rating: 5, swell_1_size: nil, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: 45, image_url: "/images/bellsbeach.jpg", date: 19750503, time: nil)
LogEntry.create(user_id: 10, public: true, surf_spot_id: 8, country_id: 3, rating: 5, swell_1_size: 10, swell_1_direction: "SSW", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: nil, image_url: "/images/teahupoo.jpg", date: 20090615, time: nil)
LogEntry.create(user_id: 11, public: true, surf_spot_id: 9, country_id: 1, rating: 5, swell_1_size: 4, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: 21, image_url: "/images/jerricho.jpg", date: 19790623, time: nil)
LogEntry.create(user_id: 12, public: true, surf_spot_id: 1, country_id: 1, rating: 3, swell_1_size: nil, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: nil, image_url: "/images/malibu.jpg", date: 19590801, time: nil)
LogEntry.create(user_id: 13, public: true, surf_spot_id: 3, country_id: 1, rating: 4, swell_1_size: 5, swell_1_direction: "NW", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: 7, wind_direction: "SE", wave_count: 15, image_url: "/images/mikesurf3.jpg", date: 20121221, time: nil)
LogEntry.create(user_id: 13, public: true, surf_spot_id: 10, country_id: 1, rating: 4, swell_1_size: 6, swell_1_direction: "", swell_2_size: nil, swell_2_direction: "", swell_3_size: nil, swell_3_direction: "", wind_speed: nil, wind_direction: "", wave_count: 25, image_url: "/images/mikeysurf1.jpg", date: 20130118, time: nil)

Post.create(log_entry_id: 1, user_id: 1, content: "I'm the king of malibu! No hodad can top this hotdogger! I surfed every single wave in the curl all day!")
Post.create(log_entry_id: 2, user_id: 2, content: "Crikey, what a blast! I got so tubed! After every tube I was frothin' for more, mate!")
Post.create(log_entry_id: 3, user_id: 3, content: "What can I say? Best waves of my life? Always trying to get that epic sesh!")
Post.create(log_entry_id: 4, user_id: 3, content: "It got really packed! Even though I'm the most famous surfer in the world I still have to fight for waves!")
Post.create(log_entry_id: 5, user_id: 3, content: "Sometimes you just have to build the perfect wave and fense it in to get waves to yourself.")
Post.create(log_entry_id: 6, user_id: 4, content: "The storm broke the pier in half! I paddle out and got this one from the boneyard! One and done!")
Post.create(log_entry_id: 7, user_id: 5, content: "Hurricane Marie was pumpin, man! Couldn't believe how solid the waves were. Oh, man. You should have been there!")
Post.create(log_entry_id: 8, user_id: 6, content: "OMG! I love surfing seal when it's that good! So fun!")
Post.create(log_entry_id: 9, user_id: 7, content: "Man, I got some humdingers and a couple of whoppers! One wave was a doozy!")
Post.create(log_entry_id: 10, user_id: 8, content: "Well, the surf session was really swell. Ha! Ya see what I did there?")
Post.create(log_entry_id: 11, user_id: 9, content: "Damn! It was epic! Best Day ever!")
Post.create(log_entry_id: 12, user_id: 10, content: "After locking in Teahupoo like I did today everyone will know I can hold my own in the world of Surfing!")
Post.create(log_entry_id: 13, user_id: 11, content: "Wow! Do I look great! I love that bathing suit! I was on the nose and carving the curl all day!")
Post.create(log_entry_id: 14, user_id: 12, content: "For all who were out surfing, I have a message. Don't Snake Me!")
Post.create(log_entry_id: 15, user_id: 13, content: "SSSSSSSSSSUUUUUUUUUUUUUUURRRRRRRRFFFFFF!!!! I love surfing!  I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing! I love surfing!")
Post.create(log_entry_id: 16, user_id: 13, content: "I had to give a hard stare to all the kooks in the water that day so they wouldn't try to burn me!")

Post.create(log_entry_id: 11, user_id: 13, content: "I'm Drooling over that photo man!")
Post.create(log_entry_id: 3, user_id: 13, content: "You're my idol.")
Post.create(log_entry_id: 5, user_id: 13, content: "WWWWWwhhhhhhhhaaaattttt!?")
Post.create(log_entry_id: 5, user_id: 1, content: "This place stinks!")
Post.create(log_entry_id: 5, user_id: 4, content: "Nothing authentic going on here.")
Post.create(log_entry_id: 9, user_id: 6, content: "Love it! Surfing here is so fun!")
Post.create(log_entry_id: 13, user_id: 8, content: "Born and raised surfing this spot. Always worth the sinus infections.")
Post.create(log_entry_id: 1, user_id: 9, content: "Dude!")
Post.create(log_entry_id: 13, user_id: 7, content: "I surfed Seal Beach Jetty that day. Looks like I should have made the drive.")
Post.create(log_entry_id: 16, user_id: 13, content: "Did I mention the kooks?")
Post.create(log_entry_id: 2, user_id: 11, content: "Wow! I need to get back to Oz.")
Post.create(log_entry_id: 12, user_id: 8, content: "Never seen anything like it!")
Post.create(log_entry_id: 10, user_id: 11, content: "Nice!")
Post.create(log_entry_id: 10, user_id: 8, content: "You get it!? :)")
Post.create(log_entry_id: 4, user_id: 9, content: "I can remember what it felt like to surf alone.")
Post.create(log_entry_id: 8, user_id: 2, content: "I was once attacked by a shark. I felt like a helpless seal.")
Post.create(log_entry_id: 1, user_id: 13, content: "Old School!")

Friendship.create(user_id: 13, friend_id: 3, confirmed: true)
Friendship.create(user_id: 3, friend_id: 13, confirmed: true)
Friendship.create(user_id: 10, friend_id: 3, confirmed: true)
Friendship.create(user_id: 3, friend_id: 10, confirmed: true)
Friendship.create(user_id: 7, friend_id: 3, confirmed: true)
Friendship.create(user_id: 3, friend_id: 7, confirmed: true)
Friendship.create(user_id: 1, friend_id: 3, confirmed: true)
Friendship.create(user_id: 3, friend_id: 1, confirmed: true)
Friendship.create(user_id: 5, friend_id: 3, confirmed: true)
Friendship.create(user_id: 3, friend_id: 5, confirmed: true)
Friendship.create(user_id: 6, friend_id: 3, confirmed: true)
Friendship.create(user_id: 3, friend_id: 6, confirmed: true)
Friendship.create(user_id: 13, friend_id: 4, confirmed: true)
Friendship.create(user_id: 4, friend_id: 13, confirmed: true)
Friendship.create(user_id: 13, friend_id: 7, confirmed: true)
Friendship.create(user_id: 7, friend_id: 13, confirmed: true)
Friendship.create(user_id: 13, friend_id: 11, confirmed: true)
Friendship.create(user_id: 11, friend_id: 13, confirmed: true)
Friendship.create(user_id: 2, friend_id: 7, confirmed: true)
Friendship.create(user_id: 7, friend_id: 2, confirmed: true)
Friendship.create(user_id: 7, friend_id: 10, confirmed: true)
Friendship.create(user_id: 10, friend_id: 7, confirmed: true)
Friendship.create(user_id: 5, friend_id: 10, confirmed: true)
Friendship.create(user_id: 10, friend_id: 5, confirmed: true)
Friendship.create(user_id: 9, friend_id: 6, confirmed: true)
Friendship.create(user_id: 6, friend_id: 9, confirmed: true)
Friendship.create(user_id: 8, friend_id: 7, confirmed: false)
